(part "SYPS-2-22HP+"
    (packageRef "SYPS222HP")
    (interface
        (port "1" (symbPinId 1) (portName "GROUND_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GROUND_2") (portType INOUT))
        (port "4" (symbPinId 3) (portName "PORT_2") (portType INOUT))
        (port "5" (symbPinId 4) (portName "PORT_1") (portType INOUT))
        (port "6" (symbPinId 5) (portName "GROUND_3") (portType INOUT))
        (port "8" (symbPinId 6) (portName "SUM_PORT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "SYPS-2-22HP+")
    (property "Mouser_Part_Number" "139-SYPS-2-22HP")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Mini-Circuits/SYPS-2-22HP%2b?qs=xZ%2FP%252Ba9zWqY1riY9ziwtAg%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "RF Power Divider 2 MHz ~ 200 MHz Isolation (Min) 18dB, 1.45 VSWR (Max), 4 Imbalance (Max) 6-SMD, No Lead")
    (property "Datasheet_Link" "https://www.minicircuits.com/pdfs/SYPS-2-22HP+.pdf")
    (property "symbolName1" "SYPS-2-22HP+")
)
